### ISSUE TITLE
use https instead of git protocol in manifest

### ISSUE THREAD

**Issue by jlmalet** [osmandapp/OsmAnd-manifest#1]
Hi,
please, think of people living behind a proxy.... android_build.xml
must have 
    <remote
        name="origin"
        fetch="https://github.com/" />
to work correctly with a proxy
thanks

**Comment by jmakovicka** [comment]
https:// is going to be mandatory from March 2022.

https://github.blog/2021-09-01-improving-git-protocol-security-github/
